# Generated by Django 2.1.2 on 2020-04-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='group_show_open',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='lesson',
            field=models.IntegerField(choices=[(1, '數學解題程式設計(1)：使用Python3')], default=2, verbose_name='課程名稱'),
        ),
    ]
