# Generated by Django 2.2.6 on 2020-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='page',
        ),
        migrations.AddField(
            model_name='annotation',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
