# Generated by Django 2.1.2 on 2020-04-27 09:28

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200417_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='groupshow',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
