# Generated by Django 2.1.2 on 2020-04-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200427_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='score_memo0',
            new_name='score_memo',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='groupshow',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='score_memo0_custom',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='score_memo1',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='score_memo1_custom',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='score_memo2',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='score_memo2_custom',
        ),
    ]
