# Generated by Django 2.0.7 on 2020-04-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200427_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='helps',
            field=models.IntegerField(default=0),
        ),
    ]
