# Generated by Django 2.0.7 on 2020-05-19 07:04

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200427_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('lesson_id', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='work',
            name='helps',
            field=models.IntegerField(choices=[(0, '全部靠自己想'), (1, '同學幫一點忙'), (2, '同學幫很多忙'), (3, '解答幫一點忙'), (4, '解答幫很多忙'), (5, '老師幫一點忙'), (6, '老師幫很多忙')], default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='memo_c',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='memo_e',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='work',
            name='picture',
            field=models.ImageField(default='/static/python/null.jpg', upload_to=student.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='work',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='youtube',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='score',
            field=models.IntegerField(default=-2),
        ),
    ]
