# Generated by Django 2.0.7 on 2020-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200428_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('lesson_id', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
