# Generated by Django 2.2.6 on 2020-06-01 08:59

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='score_memo2',
            field=models.IntegerField(default=0, verbose_name='自訂作業心得成績'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='group',
            field=models.IntegerField(default=-1, verbose_name='組別'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='score_memo',
            field=models.IntegerField(default=0, verbose_name='指定作業心得成績'),
        ),
        migrations.AlterField(
            model_name='work',
            name='code',
            field=models.TextField(default='', verbose_name='程式碼'),
        ),
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.TextField(default='', verbose_name='評語回饋'),
        ),
        migrations.AlterField(
            model_name='work',
            name='helps',
            field=models.IntegerField(choices=[(0, '全部靠自己想'), (1, '同學幫一點忙'), (2, '同學幫很多忙'), (3, '解答幫一點忙'), (4, '解答幫很多忙'), (5, '老師幫一點忙'), (6, '老師幫很多忙')], default=0, verbose_name='創作過程'),
        ),
        migrations.AlterField(
            model_name='work',
            name='memo',
            field=models.TextField(verbose_name='心得感想'),
        ),
        migrations.AlterField(
            model_name='work',
            name='picture',
            field=models.ImageField(default='/static/python/null.jpg', upload_to=student.models.upload_path_handler, verbose_name='執行結果'),
        ),
        migrations.AlterField(
            model_name='work',
            name='score',
            field=models.IntegerField(default=-2, verbose_name='成績'),
        ),
        migrations.AlterField(
            model_name='work',
            name='scorer',
            field=models.IntegerField(default=0, verbose_name='評分人id'),
        ),
    ]
