# Generated by Django 2.0.7 on 2020-05-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200514_0937'),
        ('student', '0007_answer'),
    ]

    operations = [
    ]
