# Generated by Django 2.0.7 on 2020-06-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200601_1659'),
        ('student', '0008_auto_20200601_1503'),
    ]

    operations = [
    ]
