# Generated by Django 2.0.7 on 2020-07-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_merge_20200603_1008'),
        ('student', '0010_auto_20200701_1018'),
    ]

    operations = [
    ]
